### ISSUE TITLE
code editor duplicate  row

### ISSUE THREAD

**Issue by ddkwork** [mirzakhany/chapar#18]
Hello, I have a question for you: I've been researching for days but I don't know exactly how to get the current line of the code editor, I want to copy the current line and insert it while holding down ctrl+d, do you have any hints? Thank you!
```go

		if k.Modifiers.Contain(key.ModShortcut) {
			switch k.Name {
			case "D": // copy line todo
				c.editor.Insert("//todo get current line text and  duplicate it")
				//c.lines
				gtx.Execute(op.InvalidateCmd{})
				break
			}
		}

```

**Comment by ddkwork** [comment]
In addition, the scrollbar of the list widget does not seem to register events, I don't understand: the scrolling behavior of the edit area should be controlled by the list widget, if so, we need to alias the scrollbar widget type of the list to the local area, and define its scrolling event and trigger the registered scrolling event behavior, so that when the event is obtained, the layout is refreshed so that the coordinates of the highlighted rendering overlap with the coordinates of the editing area. I'm not sure if my logic is correct though, and I need your further confirmation.
![{4F7D4BB0-CFCF-43c3-A698-BED180F5D73C}.png](https://github.com/mirzakhany/chapar/assets/19886504/4e91860b-db2c-4010-a6a5-ea4c10e51951)

**Comment by mirzakhany** [comment]
It would be very nice to add this duplicate functionality to code editor, it's kinda limited by abilities of gioui framework. unfortunately their api is not givin us access to the underlying text editor. 
and again unfortunately its the same issue with scroller bar and styled text. 

I'll try to solve this issues in gio framework.

**Comment by ddkwork** [comment]
> It would be very nice to add this duplicate functionality to code editor, it's kinda limited by abilities of gioui framework. unfortunately their api is not givin us access to the underlying text editor. 
> and again unfortunately its the same issue with scroller bar and styled text. 
> 
> I'll try to solve this issues in gio framework. 

I see, and in that case, I have an idea: it's unlikely that a proposal to let them export something would make us fork one and force a point to our version inside the mod. In addition, in order to refresh their commits in real time, we need to make minimal changes in the fork repository, and then we will make a path script that can easily replace any version with one click. What do you think of this idea

**Comment by ddkwork** [comment]
This was followed by AI code completion until I found a suitable small model. Also, can a split layout be split vertically? This will be used for the packet capture layout or the ollydbg debugger layout

**Comment by ddkwork** [comment]
I've gotten the controllable scroll-down behavior of the code editor through the cursor, and scrolling up only needs to register a scroll event to get it, and horizontal left and right scrolling has not been tested. Unfortunately, the rich text editor doesn't have scrollbars or offset coordinates to refresh the position, so after solving this, optimize the performance of loading large files to add the AI model auto-coding test. It is theoretically possible to copy the line: just get the cursor line number and then wrap the line character to insert it, and in addition, it is possible to copy the selected area for cloning. I also figured out the idea of the tree table, and the rest is all about the details. I haven't been researching GIO for 20 days, and I feel like I'm on my own, and it's useless to ask others.
